### ISSUE TITLE
running:  ['which', 'purs'] Cannot find purs in PATH

### ISSUE THREAD

**Issue by Boscop** [b123400/purescript-ide-sublime#7]
It doesn't find `purs` even though it's in my PATH on Windows.
In the console it says:
```
running:  ['which', 'purs']
Cannot find purs in PATH
```
But `which` doesn't exist on Windows. But `where` exists: `where purs` would work.

**Comment by Boscop** [comment]
But when I set it manually `"purs_path": "C:\\Users\\me\\AppData\\Roaming\\npm\\purs",` it says `OSError: [WinError 193] %1 is not a valid Win32 application` so it has to be `"C:\\Users\\me\\AppData\\Roaming\\npm\\purs.cmd"`, but then I get these errors when I save a .purs file:
```
purs ide server for D:\docs\purescript-halogen-template\ is alrady started
2017-12-27 12:49:50,032: 11788: DEBUG: on_activated
2017-12-27 12:49:51,607: 11788: DEBUG: on_hover
running:  ['C:\\Users\\me\\AppData\\Roaming\\npm\\purs.cmd', 'ide', 'client', '--port', '4242']
b"Couldn't connect to purs ide server on port PortNumber 4242:\r\n"
b'Network.Socket.connect: <socket: 328>: failed (Connection refused (WSAECONNREFUSED))\r\n'
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
purescript-ide-sublime error 1 b"Couldn't connect to purs ide server on port PortNumber 4242:\r\nNetwork.Socket.connect: <socket: 328>: failed (Connection refused (WSAECONNREFUSED))\r\n"
Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\sublime_plugin.py", line 625, in on_hover
    vel.on_hover(point, hover_zone)
  File "ide.type_hints in C:\Users\me\AppData\Roaming\Sublime Text 3\Installed Packages\PureScript.sublime-package", line 26, in on_hover
  File "ide.type_hints in C:\Users\me\AppData\Roaming\Sublime Text 3\Installed Packages\PureScript.sublime-package", line 90, in show_type_hint
  File "ide.command in C:\Users\me\AppData\Roaming\Sublime Text 3\Installed Packages\PureScript.sublime-package", line 296, in get_module_imports
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded
```
